# Generated by Django 5.1.4 on 2024-12-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='song_schedule',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=255)),
                ('singer_name', models.CharField(max_length=255)),
                ('song_image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('song_file_path', models.CharField(max_length=255)),
                ('song_category', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
